BBS/BBS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import views
from django.views.static import serve
from BBS import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 全文检索,搜索功能
    url(r'^search/', include('haystack.urls')),

    # restful
    url(r'^users/$', views.Users.as_view()),
    url(r'^users2/$', views.user2),

    url(r'^$', views.home),
    # 注册
    url(r'^register/$', views.register),
    # 登入
    url(r'^login/$', views.login),
    # 随机验证码
    url(r'^get_valid_code/$', views.get_valid_code),
    # 博客主页
    url(r'^index/$', views.index),
    # 退出
    url(r'^login_out/$', views.login_out),
    # 修改密码
    url(r'^change_password/$', views.change_password),
    # error错误信息
    url(r'^error/$', views.error),
    # 修改头像
    url(r'^change_avatar/$', views.change_avatar),
    # 点赞点踩
    url(r'^diggit/$', views.diggit),
    # 点评
    url(r'^comment/$', views.comment),
    # 后台管理
    url(r'^backend/$', views.backend),
    # 后台添加文章
    url(r'^add_article/$', views.add_article),
    # 文章修改
    url(r'^modification_article/$', views.modification_article),
    # 删除文章
    url(r'^delete_article/$', views.delete_article),
    # 添加文章上传图片add_img
    url(r'^add_img/$', views.add_img),

    # 个人站点的文章详情路由
    url(r'^(?P<username>\w+)/article/(?P<article_id>\d+)', views.article_detail),
    # 个人站点的分类路由
    url(r'^(?P<username>\w+)/(?P<condition>category|tag|archive)/(?P<param>.*)', views.blog_site),
    # media文件夹配置,用户可以无限制访问
    url(r'^media(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
    # 个人站点
    url(r'^(?P<username>\w+)', views.blog_site),
]

BBS/blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


# auth模块用户表
class UserInfo(AbstractUser):
    mobile_phone=models.BigIntegerField(null=True,blank=True)
    # auto_now_add=True自动添加
    create_time=models.DateTimeField(auto_now_add=True)
    # 添加头像字段,upload_to自动保存到指定文件夹,default设定默认图片
    avatar=models.FileField(upload_to="avatar/",default="avatar/default.png")
    # 博客表外键关联
    blog=models.OneToOneField(to="Blog",to_field="id",null=True)

    # 打印该对象时,显示username
    def __str__(self):
        return self.username

    # 在admin后台中,使表名为中文
    # class Meta:
    #     verbose_name='用户表'
    #     verbose_name_plural=verbose_name


# 博客表,个人站点表
class Blog(models.Model):
    # 站点名称
    site_name=models.CharField(max_length=32)
    # 站点标题
    site_title=models.CharField(max_length=32)
    # 个人主题,可以设置成站点的个性化样式css文件
    theme=models.CharField(max_length=32)

    def __str__(self):
        return self.site_name

# 分类表
class Category(models.Model):
    # 分类名称
    name=models.CharField(max_length=32)
    # 站点外键
    blog=models.ForeignKey(to="Blog",to_field="id",null=True)
    def __str__(self):
        return self.name


# 标签表
class Tag(models.Model):
    # 标签名称
    name=models.CharField(max_length=32)
    # 站点外键
    blog = models.ForeignKey(to="Blog", to_field="id", null=True)

    def __str__(self):
        return self.name

# 文章表
class Article(models.Model):
    # 文章标题
    title=models.CharField(max_length=64)
    # 文章概要
    summary=models.CharField(max_length=255)
    # 文章内容,用大文本字段TextField()
    content=models.TextField()
    # 文章创建时间
    var_time=models.DateTimeField(auto_now_add=True)
    # 文章分类,可以为空
    category=models.ForeignKey(to="Category",to_field='id',null=True)
    # 与标签表的多对多关联
    tag=models.ManyToManyField(to="Tag",through="ArticleToTag",through_fields=("article_id","tag_id"))
    # 文章表中添加评论数,方便查询
    comment_num=models.IntegerField(default=0)
    # 文章表中添加点赞数,方便查询
    up_num = models.IntegerField(default=0)
    # 文章表中添加点踩数,方便查询
    down_num = models.IntegerField(default=0)
    # 站点外键
    blog = models.ForeignKey(to='Blog', to_field='id', null=True)

    def __str__(self):
        return self.title



# 文章与标签的中间表
class ArticleToTag(models.Model):
    article_id=models.ForeignKey(to="Article",to_field="id")
    tag_id=models.ForeignKey(to="Tag",to_field="id")

# 点赞点踩表
class UpAndDown(models.Model):
    # 点击用户外键关联
    user=models.ForeignKey(to="UserInfo",to_field='id')
    # 点击的那篇文章外键关联
    article=models.ForeignKey(to="Article",to_field='id')
    # 点赞点踩用bool类型表示,True为赞,False为踩
    is_up=models.BooleanField()

# 评论表
class Comment(models.Model):
    # 评论用户外键关联
    user = models.ForeignKey(to="UserInfo", to_field='id')
    # 评论的那篇文章外键关联
    article = models.ForeignKey(to="Article", to_field='id')
    # 评论内容
    content = models.CharField(max_length=255)
    # 子评论自关联
    parent = models.ForeignKey(to='Comment', to_field='id', null=True,blank=True)
    # 评论创建时间
    comment_time = models.DateTimeField(auto_now_add=True)

BBS/templates/backends/add_article.html
{% extends "backends/backend_base.html" %}
{% block backend %}
    <div>
        <p>添加文章</p>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="">标题</label>
                <input type="text" name="title" class="form-control">
            </div>
            <p>内容(Kindeditor编辑器，不支持拖放/粘贴上传图片)</p>
            <textarea name="content" id="id_content" cols="30" rows="10"></textarea>
            <hr>
            <div class="form-group">
                <h4>标签分类</h4>
                {% for tag in tags %}
                    <label for="tag{{ tag.pk }}">{{ tag.name }}</label>
                    <input type="radio" name="tag" value="{{ tag.pk }}" id="tag{{ tag.pk }}">
                {% endfor %}

            </div>
            <hr>
            <div class="form-group">
                <h4>文章分类</h4>
                {% for category in categorys %}
                    <label for="category{{ category.pk }}">{{ category.name }}</label>
                    <input type="radio" name="category" value="{{ category.pk }}" id="category{{ category.pk }}">
                {% endfor %}

            </div>
            <p><input type="submit" value="提交" class="btn btn-danger"></p>
        </form>
    </div>

{% endblock %}

{% block add_article %}
    <script charset="utf-8" src="/static/kindeditor-master/kindeditor-all-min.js"></script>
    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#id_content', {
                width: '100%',
                height: '450px',
                //items的作用
                resizeType: 0,
                //上传文件的路由
                uploadJson: '/add_img/',
                /*
                extraFileUploadParams : {
                        csrfmiddlewaretoken : '{{ csrf_token }}',
                }
                */
            });
        });
    </script>


{% endblock %}

BBS/templates/backends/backend.html
{% extends "backends/backend_base.html" %}
{% block backend %}
    <table class="table table-striped">
    <thead>
    <tr>
        <th>标题</th>
        <th>评论数</th>
        <th>点赞数</th>
        <th>操作</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for article in article_list %}
    <tr>
    <td><a href="/{{ request.user.username }}/article/{{ article.pk }}">{{ article.title }}</a></td>
    <td>{{ article.comment_num }}</td>
    <td>{{ article.up_num }}</td>
    <td><a href="/modification_article/?article_id={{ article.pk }}">修改</a></td>
    <td><a href="/delete_article/?article_id={{ article.pk }}">删除</a></td>
    </tr>
    {% endfor %}

    </tbody>
    </table>

{% endblock %}

BBS/templates/backends/backend_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>后台管理</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <style>
        .header {
            height: 100px;
            background: cornflowerblue;
        }

        .right, .light {
            line-height: 100px;
            font-size: 20px;
            color: black;
        }

        .right:hover {
            text-decoration: none;
        }

        .light:hover {
            text-decoration: none;
        }
    </style>
</head>
<body>
<div class="header">
    <div class="col-md-3">
        <a href="/index/" class="light">
            <span class="label label-default" style="font-size: 30px;">欢迎你来博客园</span>
        </a>
    </div>
    <div class="col-md-7"></div>
    <div class="col-md-2">
        <a href="/backend/" class="right">
            <span >{{ request.user }}的后台管理</span>
        </a>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                               aria-expanded="true" aria-controls="collapseOne">
                                操作
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body">
                            <a href="/add_article/">添加文章</a>
                        </div>
                        <div class="panel-body">
                            <a href="">添加随笔</a>
                        </div>
                        <div class="panel-body">
                            <a href="">其它</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-10">
            <div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab"
                                                              data-toggle="tab">文章</a></li>
                    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab"
                                               data-toggle="tab">随笔</a></li>
                    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab"
                                               data-toggle="tab">园子</a></li>
                    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab"
                                               data-toggle="tab">交友</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="home">
                        {% block backend %}

                        {% endblock %}
                    </div>
                    <div role="tabpanel" class="tab-pane" id="profile">随笔页面</div>
                    <div role="tabpanel" class="tab-pane" id="messages">园子页面</div>
                    <div role="tabpanel" class="tab-pane" id="settings">交友页面</div>
                </div>
            </div>
        </div>
    </div>
</div>


</body>
<script src="/static/JS/jquery-3.3.1.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
{% block add_article %}
{% endblock %}
</html>

BBS/templates/backends/modification_article.html
{% extends "backends/backend_base.html" %}
{% block backend %}
    <div>
        <p>添加文章</p>
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="article_id" value="{{ article.pk }}">
            <div class="form-group">
                <label for="">标题</label>
                <input type="text" name="title" class="form-control" value="{{ article.title }}">
            </div>
            <p>内容(Kindeditor编辑器，不支持拖放/粘贴上传图片)</p>
            <textarea name="content" id="id_content" cols="30" rows="10">{{ article.content|safe }}</textarea>
            <hr>
            <div class="form-group">
                <h4>标签分类</h4>
                {% for tag in tags %}
                    {% if  tag.pk == article_to_tag.tag_id_id %}
                        <label for="tag{{ tag.pk }}">{{ tag.name }}</label>
                        <input type="radio" name="tag" value="{{ tag.pk }}" id="tag{{ tag.pk }}" checked>
                    {% else %}
                        <label for="tag{{ tag.pk }}">{{ tag.name }}</label>
                        <input type="radio" name="tag" value="{{ tag.pk }}" id="tag{{ tag.pk }}">
                    {% endif %}

                {% endfor %}
            </div>
            <div class="form-group">
                <h4>文章分类</h4>
                {% for category in categorys %}
                    {% if category.pk == article.category_id %}
                        <label for="category{{ category.pk }}">{{ category.name }}</label>
                        <input type="radio" name="category" value="{{ category.pk }}" id="category{{ category.pk }}" checked>
                    {% else %}
                        <label for="category{{ category.pk }}">{{ category.name }}</label>
                        <input type="radio" name="category" value="{{ category.pk }}" id="category{{ category.pk }}">
                    {% endif %}
                {% endfor %}

            </div>

            <p><input type="submit" value="提交" class="btn btn-danger"></p>
        </form>
    </div>

{% endblock %}

{% block add_article %}
    <script charset="utf-8" src="/static/kindeditor-master/kindeditor-all-min.js"></script>
    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#id_content', {
                width: '100%',
                height: '450px',
                //items的作用
                resizeType: 0,
                //上传文件的路径
                uploadJson: '/add_img/',
            });
        });
    </script>


{% endblock %}